apiVersion: v1
kind: Pod
metadata:
  name: rajbir-sauce-ubuntu-1604-5
  namespace: cloudservices-shared
  labels:
    purpose: open sauce connect tunnel
spec:
  containers:
  - name: rajbsoodsauce-ubuntu-1604-5
    image: debian
    ports:
   - containerPort: 8000
    command: ["/bin/bash"]
    args: ["-c", "while true; do echo hello; sleep 20; done"]
  restartPolicy: OnFailure
